# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# 依赖于package-lock.json,如果没有 package-lock.json workflow 会报错
#  只有pnpm-lock.yaml 不起作用

name: Node.js CI
# 触发条件
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
#
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'
          cache: 'pnpm'

      # - run: npm ci
      #- run: npm run build --if-present

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: npm run build
        run: npm run build --if-present

      # - run: npm test

      # step2: deployment
      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0.2
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-e -c -r --delete'
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: './dist/'
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
